import type { Metadata } from "next";
import { cookies } from "next/headers";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import NavBar from "@/components/navbar";
import { Toaster } from "@/components/ui/sonner";

const interFont = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: {
    template: "%s • ApexLens",
    default: "ApexLens",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookieStore = cookies();
  const theme = cookieStore.get("theme");

  return (
    <html
      lang="en"
      className={cn(
        "w-full h-full relative",
        theme?.value === "light" ? "" : "dark"
      )}
    >
      <body
        className={cn(
          "w-full h-full relative",
          "bg-background font-sans antialiased",
          interFont.variable,
          interFont.className
        )}
      >
        <NavBar>{children}</NavBar>

        {/* Toasts */}
        <Toaster
          closeButton
          richColors
          theme={theme?.value === "light" ? "light" : "dark"}
        />
      </body>
    </html>
  );
}
