import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import NavBar from "@/components/navbar";

const interFont = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={cn("w-full h-full relative", "dark")}>
      <body
        className={cn(
          "w-full h-full relative",
          "bg-background font-sans antialiased",
          interFont.variable,
          interFont.className
        )}
      >
        <NavBar>{children}</NavBar>
      </body>
    </html>
  );
}
